[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remapping = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
solc_version = "0.8.20"

ffi = true
fs_permissions = [{access = "read", path = "./img"}]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
